name: Generate static org-roam-ui page
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Generate org-roam-ui page
        uses: ikoamu/publish-org-roam-ui@main
        with:
          org-roam-db-filename: roam.db
          deploy-to-pages: true
